{% set name = "autogluon.timeseries" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ea0ba655362984d8f9c6652cc3e233ff405ec94b80901f75c2e5407959c49707

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./timeseries -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - RELEASE=1

requirements:
  host:
    - python {{ python_min }}
    - packaging
    - pip
    - setuptools
  run:
    # See https://pypi.org/pypi/autogluon.timeseries/{{ version }}/json
    - python >={{ python_min }}
    - autogluon.core =={{ version }}
    - autogluon.common =={{ version }}
    - autogluon.tabular =={{ version }}
    - accelerate <2.0,>=0.34.0
    - orjson >=3.9,<4.dev0
    - tensorboard <3,>=2.9
    - transformers <5,>=4.38.0
    - sentencepiece !=0.1.92,>=0.1.91  # via transformers sentencepiece extras
    - utilsforecast <0.2.11,>=0.2.3
    - joblib <2,>=1.1
    - numpy <2.3.0,>=1.25
    - scipy <1.16,>=1.5.4
    - pandas <2.3.0,>=2.0.0
    - gluonts <0.17,>=0.15.0
    - pytorch >=2.2,<2.7
    - pytorch-lightning >=2.2,<2.7
    - networkx <4,>=3.0
    - statsforecast <2.0.2,>=1.7.0
    - mlforecast >=0.13.4,<0.14
    - coreforecast
    - fugue >=0.9.0
    - tqdm <5,>=4.38

test:
  imports:
    - autogluon.timeseries
  commands:
    - python -c "from autogluon.timeseries import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'"
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/autogluon.timeseries
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Innixma
    - suzhoum
    - tonyhoo
    - prateekdesai04
