{% set name = "autogluon.timeseries" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz 
  sha256: a4d950b5c796a835c690d25dc2406ab35062a973ed70685f5b8f1e850b780bbc 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./timeseries -vv
  number: 0
  script_env:
    - RELEASE=1

requirements:
  host:
    - python >=3.8,<3.12
    - packaging
    - pip
  run:
    - python >=3.8,<3.12
    - joblib >=1.1,<2
    - numpy >=1.21,<1.29
    - scipy >=1.5.4,<1.13
    - pandas >=2.0.0,<2.2.0
    - statsmodels >=0.13.0,<0.15
    - gluonts >=0.14.0,<0.15
    - pytorch >=2.0,<2.1
    - pytorch-lightning >=2.0.0,<2.1
    - networkx >=3.0,<4
    - statsforecast >=1.4.0,<1.5
    - mlforecast >=0.10.0,<0.10.1
    - tqdm >=4.38,<5
    - ujson >=5,<6
    - autogluon.core =={{ version }}
    - autogluon.common =={{ version }}
    - autogluon.tabular =={{ version }}

test:
  imports:
    - autogluon.timeseries
  commands:
    - python -c "from autogluon.timeseries import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.timeseries
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tonyhoo
    - suzhoum
    - yinweisu
    - giswqs
    - Innixma
