{% set name = "autogluon.timeseries" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 455831de3c9de8fbe11b100054b8f150661d0651212fcfa4ec2e42417fdac355

build:
  # noarch: python
  skip: true  # [py>=311]
  script: {{ PYTHON }} -m pip install ./timeseries -vv
  number: 1
  script_env:
   - RELEASE=1

requirements:
  build:
    # - {{ compiler('cuda') }}                 # [linux and cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.21,<1.27                    # [build_platform != target_platform]
    # - pybind11                               # [build_platform != target_platform]
  host:
    - python  # >=3.8,<3.11
    - packaging
    - pip
  run:
    - python  # >=3.8,<3.11
    - joblib >=1.1,<2
    - numpy >=1.21,<1.27
    - scipy >=1.5.4,<1.12
    - pandas >=1.4.1,<1.6
    - statsmodels >=0.13.0,<0.14
    - gluonts >=0.12.0,<0.13  # [not win]
    - pytorch >=1.9,<1.14  # [not win]
    - pytorch-lightning >=1.7.4,<1.10.0  # [not win]
    - networkx >=2.3,<3.0
    - statsforecast >=1.4.0,<1.5
    - tqdm >=4.38,<5
    - ujson >=5,<6
    - sktime >=0.14,<0.16
    - pmdarima >=1.8.2,<1.9
    - tbats >=1.1,<2
    - autogluon.core =={{ version }}
    - autogluon.common =={{ version }}
    - autogluon.tabular =={{ version }}

test:
  imports:
    - autogluon.timeseries
  commands:
    - python -c "from autogluon.timeseries import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip
    # - pytorch =*=cuda*  # [linux and cuda_compiler_version != "None"]

about:
  home: https://pypi.org/project/autogluon.timeseries
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - Innixma
