{% set name = "autogluon.timeseries" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 54eb1b144cbf6980d6fb34d1ccb870f486c3ed9086d9d6e1ff84554e5cab858a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./timeseries -vv
  number: 0
  script_env:
    - RELEASE=1

requirements:
  host:
    - python >=3.8,<3.11
    - packaging
    - pip
  run:
    - accelerate <0.22.0,>=0.21.0
    - lightning <2.4,>=2.2
    - orjson >=3.9,<4.dev0
    - tensorboard <3,>=2.9
    - transformers <4.41.0,>=4.38.0
    - utilsforecast <0.0.11,>=0.0.10
    - python >=3.8,<3.11
    - joblib <2,>=1.1
    - numpy <1.29,>=1.21
    - scipy <1.13,>=1.5.4
    - pandas <2.3.0,>=2.0.0
    - statsmodels >=0.13.0,<0.15
    - gluonts ==0.15.1
    - pytorch <2.4,>=2.2
    - pytorch-lightning <2.4,>=2.2
    - networkx <4,>=3.0
    - statsforecast <1.5,>=1.4.0
    - mlforecast <0.10.1,>=0.10.0
    - tqdm <5,>=4.38
    - ujson >=5,<6
    - autogluon.core ==1.1.1
    - autogluon.common ==1.1.1
    - autogluon.tabular ==1.1.1

test:
  imports:
    - autogluon.timeseries
  commands:
    - python -c "from autogluon.timeseries import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.timeseries
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - Innixma
    - suzhoum
    - tonyhu
