{% set name = "autogluon.timeseries" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://autogluon.s3.us-west-2.amazonaws.com/tarballs/1.2.0_patch/tarball.tar.gz 
  sha256: ac72aa0430b711b5eb540b01064a505d42333738bc8b1cd44649249183a647d1 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./timeseries -vv
  number: 1
  script_env:
    - RELEASE=1

requirements:
  host:
    - python >=3.9,<3.13
    - packaging
    - pip
  run:
    - accelerate >=0.34.0,<1.0
    - lightning >=2.2,<2.6
    - orjson >=3.9,<4.dev0
    - tensorboard <3,>=2.9
    - transformers <5,>=4.38.0
    - python >=3.9,<3.13
    - joblib <2,>=1.1
    - numpy >=1.25.0,<2.1.4
    - scipy >=1.5.4,<1.16
    - pandas <2.3.0,>=2.0.0
    - gluonts >=0.15.0,<0.17
    - pytorch >=2.2,<2.6
    - networkx <4,>=3.0
    - statsforecast <1.8,>=1.7.0
    - mlforecast ==0.13.4
    - sentencepiece >=0.1.91,!=0.1.92
    - utilsforecast >=0.2.3,<0.2.5
    - coreforecast ==0.0.12
    - fugue >=0.9.0
    - tqdm <5,>=4.38
    - autogluon.core =={{ version }}
    - autogluon.common =={{ version }}
    - autogluon.tabular =={{ version }}

test:
  imports:
    - autogluon.timeseries
  commands:
    - python -c "from autogluon.timeseries import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'" 
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.timeseries
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - Innixma
    - suzhoum
    - tonyhoo
    - prateekdesai04
