{% set name = "autogluon.timeseries" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://autogluon.s3.us-west-2.amazonaws.com/tarballs/0.8.3_patch_torch/tarball.tar.gz
  sha256: c4d4be30b763841884701f7af49e2cd2544a41d1fc6c0d5d14267e6259c12408 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./timeseries -vv
  number: 2
  script_env:
    - RELEASE=1

requirements:
  host:
    - python >=3.8,<3.11
    - packaging
    - pip
  run:
    - python >=3.8,<3.11
    - joblib >=1.1,<2
    - numpy >=1.21,<1.27
    - scipy >=1.5.4,<1.12
    - pandas >=2.0.0,<2.2.0
    - statsmodels >=0.13.0,<0.15
    - gluonts >=0.13.1,<0.14
    - pytorch >=2.0,<2.5
    - pytorch-lightning >=2.0.0,<2.5
    - networkx >=3.0,<4
    - statsforecast >=1.4.0,<1.5
    - mlforecast >=0.7.0,<0.7.4
    - tqdm >=4.38,<5
    - ujson >=5,<6
    - autogluon.core =={{ version }}
    - autogluon.common =={{ version }}
    - autogluon.tabular =={{ version }}

test:
  imports:
    - autogluon.timeseries
  commands:
    - python -c "from autogluon.timeseries import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'" 
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.timeseries
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - Innixma
    - suzhoum
    - tonyhoo
    - prateekdesai04
