{% set name = "autogluon.timeseries" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fd388cb91e5a9467252be061b1bb90c9735d7f543d1d8335ff75f4b362ce4d86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./timeseries -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - RELEASE=1

requirements:
  host:
    - python {{ python_min }}
    - packaging
    - pip
    - setuptools
  run:
    # See https://pypi.org/pypi/autogluon.timeseries/{{ version }}/json
    - autogluon.features ==1.3.1b20250522
    - pytorch-lightning
    - python >={{ python_min }}
    - autogluon.core ==1.3.1b20250522
    - autogluon.common ==1.3.1b20250522
    - autogluon.tabular ==1.3.1b20250522
    - accelerate >=0.34.0,<2.0
    - orjson >=3.9,<4.dev0
    - tensorboard >=2.9,<3
    - transformers >=4.38.0,<4.50
    - sentencepiece !=0.1.92,>=0.1.91  # via transformers sentencepiece extras
    - utilsforecast >=0.2.3,<0.2.11
    - joblib >=1.1,<2
    - numpy >=1.25.0,<2.3.0
    - scipy >=1.5.4,<1.16
    - pandas >=2.0.0,<2.3.0
    - gluonts >=0.15.0,<0.17
    - pytorch >=2.2,<2.7
    - lightning >=2.2,<2.7
    - networkx >=3.0,<4
    - statsforecast >=1.7.0,<2.0.2
    - mlforecast >0.13,<0.14
    - coreforecast >=0.0.12,<0.0.16
    - fugue >=0.9.0
    - tqdm >=4.38,<5

test:
  imports:
    - autogluon.timeseries
  commands:
    - python -c "from autogluon.timeseries import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'"
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/autogluon.timeseries
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Innixma
    - suzhoum
    - tonyhoo
    - prateekdesai04
