{% set name = "autogluon.timeseries" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f10b1ab4cb33a1b0c6b626a2e99c471bf892626e315adcb95f2fe3c495b48448

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./timeseries -vv
  number: 3
  script_env:
    - RELEASE=1

requirements:
  host:
    - python >=3.8,<3.11
    - packaging
    - pip
  run:
    - accelerate <0.30.0,>=0.21.0
    - lightning >=2.1,<2.4
    - orjson >=3.9,<4.dev0
    - tensorboard <3,>=2.9
    - transformers <5,>=4.38.0
    - utilsforecast <0.0.11,>=0.0.10
    - python >=3.8,<3.11
    - joblib <2,>=1.1
    - numpy <1.29,>=1.21
    - scipy <1.13,>=1.5.4
    - pandas <2.3.0,>=2.0.0
    - statsmodels >=0.13.0,<0.15
    - gluonts <0.14.4,>=0.14.0
    - pytorch >=2.1,<2.4
    - pytorch-lightning >=2.1,<2.4
    - networkx <4,>=3.0
    - statsforecast <1.5,>=1.4.0
    - mlforecast <0.10.1,>=0.10.0
    - tqdm <5,>=4.38
    - ujson >=5,<6
    - autogluon.core =={{ version }}
    - autogluon.common =={{ version }}
    - autogluon.tabular =={{ version }}

test:
  imports:
    - autogluon.timeseries
  commands:
    - python -c "from autogluon.timeseries import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.timeseries
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tonyhoo
    - suzhoum
    - giswqs
    - Innixma
    - prateekdesai04
